package trismegistoplanilla.utilities;

public class EmailDesign {

  public static String correoDesign(String codigoVerificacion, String enlace) {
    String html = "<!doctype html>\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\"\n"
            + "xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
            + "  \n"
            + "  <head>\n"
            + "    <title></title>\n"
            + "    <!--[if !mso]>\n"
            + "      <!-- -->\n"
            + "      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
            + "    <!--<![endif]-->\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            + "    <style type=\"text/css\">\n"
            + "      #outlook a { padding: 0; }\n"
            + "      .ReadMsgBody { width: 100%; }\n"
            + "      .ExternalClass { width: 100%; }\n"
            + "      .ExternalClass * { line-height:100%; }\n"
            + "      body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }\n"
            + "      table, td { border-collapse:collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }\n"
            + "      img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }\n"
            + "      p { display: block; margin: 13px 0; }\n"
            + "    </style>\n"
            + "    <!--[if !mso]>\n"
            + "      <!-->\n"
            + "      <style type=\"text/css\">\n"
            + "        @media only screen and (max-width:480px) {\n"
            + "          @-ms-viewport { width:320px; }\n"
            + "          @viewport { width:320px; }\n"
            + "        }\n"
            + "      </style>\n"
            + "    <!--<![endif]-->\n"
            + "    <!--[if mso]>\n"
            + "      <xml>\n"
            + "        <o:OfficeDocumentSettings>\n"
            + "          <o:AllowPNG/>\n"
            + "          <o:PixelsPerInch>96</o:PixelsPerInch>\n"
            + "        </o:OfficeDocumentSettings>\n"
            + "      </xml>\n"
            + "    <![endif]-->\n"
            + "    <!--[if lte mso 11]>\n"
            + "      <style type=\"text/css\">\n"
            + "        .outlook-group-fix {\n"
            + "          width:100% !important;\n"
            + "        }\n"
            + "      </style>\n"
            + "    <![endif]-->\n"
            + "    <!--[if !mso]>\n"
            + "      <!-->\n"
            + "      <link href=\"https://d2yjfm58htokf8.cloudfront.net/static/fonts/averta-v2.css\"\n"
            + "      rel=\"stylesheet\" type=\"text/css\">\n"
            + "      <style type=\"text/css\">\n"
            + "        @import url(https://d2yjfm58htokf8.cloudfront.net/static/fonts/averta-v2.css);\n"
            + "      </style>\n"
            + "    <!--<![endif]-->\n"
            + "    <style type=\"text/css\">\n"
            + "      p {\n"
            + "        margin: 0 0 24px 0;\n"
            + "      }\n"
            + "\n"
            + "      a {\n"
            + "        color: #00b9ff;\n"
            + "      }\n"
            + "\n"
            + "      hr {\n"
            + "        margin: 32px 0;\n"
            + "        border-top: 1px #e2e6e8;\n"
            + "      }\n"
            + "\n"
            + "      dt {\n"
            + "        font-size: 13px;\n"
            + "        margin-left: 0;\n"
            + "      }\n"
            + "\n"
            + "	  dd {\n"
            + "        color: #37517e;\n"
            + "        margin-bottom: 24px;\n"
            + "        margin-left: 0;\n"
            + "      }\n"
            + "\n"
            + "      h5 {\n"
            + "        font-family: TW-Averta-SemiBold, Averta, Helvetica, Arial;\n"
            + "        font-size: 16px;\n"
            + "        line-height: 24px;\n"
            + "        color: #2e4369;\n"
            + "      }\n"
            + "      \n"
            + "      pre {\n"
            + "        display: block;\n"
            + "        padding: 16px;\n"
            + "        padding: 12px 24px;\n"
            + "        margin: 0 0 48px;\n"
            + "        font-size: 14px;\n"
            + "        line-height: 24px;\n"
            + "        color: #4a5860;\n"
            + "        word-break: break-all;\n"
            + "        word-wrap: break-word;\n"
            + "        background-color: #f2f5f7;\n"
            + "        border-radius: 3px;\n"
            + "      }\n"
            + "\n"
            + "      .body-wrapper {\n"
            + "        background: #f2f5f7 url('https://d2yjfm58htokf8.cloudfront.net/static/images/background-v1.png') no-repeat center top;\n"
            + "        padding: 0px;\n"
            + "        margin: auto;\n"
            + "      }\n"
            + "\n"
            + "      .content-wrapper {\n"
            + "        max-width: 536px;\n"
            + "        padding: 32px;\n"
            + "        padding-bottom: 48px;\n"
            + "      }\n"
            + "\n"
            + "      .footer-wrapper div {\n"
            + "        color: #37517e !important;\n"
            + "      }\n"
            + "\n"
            + "      .footer-wrapper div a {\n"
            + "        color: #00b9ff !important;\n"
            + "      }\n"
            + "\n"
            + "      .hero {\n"
            + "        font-family: TW-Averta-Bold, Averta, Helvetica, Arial;\n"
            + "        color: #37517e;\n"
            + "        font-size: 22px;\n"
            + "        line-height: 30px;\n"
            + "      }\n"
            + "\n"
            + "      .page-header {\n"
            + "        border-bottom: 1px solid #eaebed;\n"
            + "        padding-bottom: 16px;\n"
            + "      }\n"
            + "\n"
            + "      .mb-0 {\n"
            + "        margin-bottom: 0 !important;\n"
            + "      }\n"
            + "\n"
            + "      .mt-0 {\n"
            + "        margin-top: 0 !important;\n"
            + "      }\n"
            + "      \n"
            + "      .btn {\n"
            + "        box-sizing: border-box;\n"
            + "        display: inline-block;\n"
            + "        min-height: 36px;\n"
            + "        padding: 12px 24px;\n"
            + "        margin: 0 0 24px;\n"
            + "        font-size: 16px;\n"
            + "        font-weight: 600;\n"
            + "        line-height: 24px;\n"
            + "        text-align: center;\n"
            + "        white-space: nowrap;\n"
            + "        vertical-align: middle;\n"
            + "        cursor: pointer;\n"
            + "        border: 0;\n"
            + "        border-radius: 3px;\n"
            + "        color: #fff;\n"
            + "        background-color: #00b9ff;\n"
            + "        text-decoration: none;\n"
            + "\n"
            + "        -webkit-transition: all .15s ease-in-out;\n"
            + "        -o-transition: all .15s ease-in-out;\n"
            + "        transition: all .15s ease-in-out;\n"
            + "      }\n"
            + "      \n"
            + "      .btn:hover {\n"
            + "        background-color: #00a4df;\n"
            + "      }\n"
            + "      \n"
            + "      .btn:active {\n"
            + "        background-color: #008ec0;\n"
            + "      }\n"
            + "\n"
            + "      @media screen and (min-width: 576px) and (max-width: 768px) {\n"
            + "        .body-wrapper {\n"
            + "          padding: 24px !important;\n"
            + "        }\n"
            + "\n"
            + "        .content-wrapper {\n"
            + "          max-width: 504px !important;\n"
            + "          padding: 48px !important;\n"
            + "        }\n"
            + "      }\n"
            + "\n"
            + "      @media screen and (min-width: 768px) {\n"
            + "        .body-wrapper {\n"
            + "          padding: 48px !important;\n"
            + "        }\n"
            + "\n"
            + "        .content-wrapper {\n"
            + "          max-width: 456px !important;\n"
            + "          padding: 72px !important;\n"
            + "          padding-top: 48px !important;\n"
            + "        }\n"
            + "      }\n"
            + "    </style>\n"
            + "    <style type=\"text/css\">\n"
            + "      @media only screen and (min-width:480px) {\n"
            + "        .mj-column-per-100 { width:100%!important; }\n"
            + "      }\n"
            + "    </style>\n"
            + "  </head>\n"
            + "  \n"
            + "  <body>\n"
            + "    <div class=\"mj-container body-wrapper\">\n"
            + "      <!--[if mso | IE]>\n"
            + "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"\n"
            + "        align=\"center\" style=\"width:600px;\">\n"
            + "          <tr>\n"
            + "            <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\n"
            + "            <![endif]-->\n"
            + "            <div style=\"margin:0px auto;max-width:600px;background:#fff;\" class=\"content-wrapper\"\n"
            + "            data-class=\"content-wrapper\">\n"
            + "              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;background:#fff;\"\n"
            + "              align=\"center\" border=\"0\">\n"
            + "                <tbody>\n"
            + "                  <tr>\n"
            + "                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                      <!--[if mso | IE]>\n"
            + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                          <tr>\n"
            + "                            <td style=\"width:600px;\">\n"
            + "                            <![endif]-->\n"
            + "                            <div style=\"margin:0px auto;max-width:600px;\">\n"
            + "                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;\"\n"
            + "                              align=\"center\" border=\"0\">\n"
            + "                                <tbody>\n"
            + "                                  <tr>\n"
            + "                                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                                      <!--[if mso | IE]>\n"
            + "                                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                                          <tr>\n"
            + "                                            <td style=\"vertical-align:middle;width:600px;\">\n"
            + "                                            <![endif]-->\n"
            + "                                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"vertical-align:middle;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;\">\n"
            + "                                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"vertical-align:middle;\"\n"
            + "                                              width=\"100%\" border=\"0\">\n"
            + "                                                <tbody>\n"
            + "                                                  <tr>\n"
            + "                                                    <td style=\"word-wrap:break-word;font-size:0px;padding:0px;\" align=\"center\">\n"
            + "                                                      <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border-spacing:0px;\"\n"
            + "                                                      align=\"center\" border=\"0\">\n"
            + "                                                        <tbody>\n"
            + "                                                          <tr>\n"
            + "                                                            <td style=\"width:150px;\">\n"
            //                + "                                                              <img alt=\"Logo\" title=\"\" height=\"auto\" src=\"http://sacooliveros.edu.pe/images/sacooliveros/Home/logos/logo-saco-apeiron.png\"\n"
            + "                                                              <img alt=\"Logo\" title=\"\" height=\"auto\" src=\"https://farm5.staticflickr.com/4700/24780734787_9712ecc7f6_b.jpg\"\n"
            + "                                                              style=\"border:none;border-radius:0px;display:block;font-size:13px;outline:none;text-decoration:none;width:100%;height:auto;\"\n"
            + "                                                              width=\"150\">\n"
            + "                                                            </td>\n"
            + "                                                          </tr>\n"
            + "                                                        </tbody>\n"
            + "                                                      </table>\n"
            + "                                                    </td>\n"
            + "                                                  </tr>\n"
            + "                                                </tbody>\n"
            + "                                              </table>\n"
            + "                                            </div>\n"
            + "                                            <!--[if mso | IE]>\n"
            + "                                            </td>\n"
            + "                                          </tr>\n"
            + "                                        </table>\n"
            + "                                      <![endif]-->\n"
            + "                                    </td>\n"
            + "                                  </tr>\n"
            + "                                </tbody>\n"
            + "                              </table>\n"
            + "                            </div>\n"
            + "                            <!--[if mso | IE]>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                          <tr>\n"
            + "                            <td style=\"width:600px;\">\n"
            + "                            <![endif]-->\n"
            + "                            <div style=\"margin:0px auto;max-width:600px;\">\n"
            + "                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;\"\n"
            + "                              align=\"center\" border=\"0\">\n"
            + "                                <tbody>\n"
            + "                                  <tr>\n"
            + "                                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                                      <!--[if mso | IE]>\n"
            + "                                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                                          <tr>\n"
            + "                                            <td style=\"vertical-align:top;width:600px;\">\n"
            + "                                            <![endif]-->\n"
            + "                                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;\">\n"
            + "                                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                                                <tbody>\n"
            + "                                                  <tr>\n"
            + "                                                    <td style=\"word-wrap:break-word;font-size:0px;padding:0px;\">\n"
            + "                                                      <div style=\"font-size:1px;line-height:48px;white-space:nowrap;\"> </div>\n"
            + "                                                    </td>\n"
            + "                                                  </tr>\n"
            + "                                                </tbody>\n"
            + "                                              </table>\n"
            + "                                            </div>\n"
            + "                                            <!--[if mso | IE]>\n"
            + "                                            </td>\n"
            + "                                          </tr>\n"
            + "                                        </table>\n"
            + "                                      <![endif]-->\n"
            + "                                    </td>\n"
            + "                                  </tr>\n"
            + "                                </tbody>\n"
            + "                              </table>\n"
            + "                            </div>\n"
            + "                            <!--[if mso | IE]>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                          <tr>\n"
            + "                            <td style=\"width:600px;\">\n"
            + "                            <![endif]-->\n"
            + "                            <div style=\"margin:0px auto;max-width:600px;\">\n"
            + "                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;\"\n"
            + "                              align=\"center\" border=\"0\">\n"
            + "                                <tbody>\n"
            + "                                  <tr>\n"
            + "                                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                                      <!--[if mso | IE]>\n"
            + "                                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                                          <tr>\n"
            + "                                            <td style=\"vertical-align:top;width:600px;\">\n"
            + "                                            <![endif]-->\n"
            + "                                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;\">\n"
            + "                                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                                                <tbody>\n"
            + "                                                  <tr>\n"
            + "                                                    <td style=\"word-wrap:break-word;font-size:0px;padding:0px;\" align=\"left\">\n"
            + "                                                      <div style=\"cursor:auto;color:#5d7079;font-family:TW-Averta-Regular, Averta, Helvetica, Arial;font-size:16px;line-height:24px;letter-spacing:0.4px;text-align:left;\">\n"
            + "                                                        <p><h1>TRISMEGISTO - PLANILLA</h1></p>\n"
            //                + "                                                        <p class=\"hero\">TE SALUDA 'TRISMEGISTO - PLANILLA'</p>\n"
            + "                                                        <p>Hola, para proceder a registrarte por favor ingresa el siguiente código y tu número de documento con el cuál has sido registrado:</p>\n"
            + "                                                        <p> <h1>" + codigoVerificacion + "</h1> </p>\n"
            + "                                                        <p>\n"
            + "                                                          <a href=\"" + enlace + "\" class=\"btn\" mc:disable-tracking=\"\">Ir a registrarme</a>\n"
            + "                                                        </p>\n"
            + "                                                        <p>Si no sabe por qué recibió este correo electrónico, infórmenos de inmediato para que podamos solucionarlo por usted.</p>\n"
            + "                                                        <hr style=\"margin-top: 56px\">\n"
            + "                                                        <p class=\"mb-0\">Gracias,</p>\n"
            + "                                                        <p class=\"mb-0\">Área de Sistemas - TIC</p>\n"
            + "                                                      </div>\n"
            + "                                                    </td>\n"
            + "                                                  </tr>\n"
            + "                                                </tbody>\n"
            + "                                              </table>\n"
            + "                                            </div>\n"
            + "                                            <!--[if mso | IE]>\n"
            + "                                            </td>\n"
            + "                                          </tr>\n"
            + "                                        </table>\n"
            + "                                      <![endif]-->\n"
            + "                                    </td>\n"
            + "                                  </tr>\n"
            + "                                </tbody>\n"
            + "                              </table>\n"
            + "                            </div>\n"
            + "                            <!--[if mso | IE]>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                        </table>\n"
            + "                      <![endif]-->\n"
            + "                    </td>\n"
            + "                  </tr>\n"
            + "                </tbody>\n"
            + "              </table>\n"
            + "            </div>\n"
            + "            <!--[if mso | IE]>\n"
            + "            </td>\n"
            + "          </tr>\n"
            + "        </table>\n"
            + "      <![endif]-->\n"
            + "      <!--[if mso | IE]>\n"
            + "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"\n"
            + "        align=\"center\" style=\"width:600px;\" class=\"content-wrapper-outlook footer-wrapper-outlook\">\n"
            + "          <tr>\n"
            + "            <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\n"
            + "            <![endif]-->\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                        </table>\n"
            + "                      <![endif]-->\n"
            + "                    </td>\n"
            + "                  </tr>\n"
            + "                </tbody>\n"
            + "              </table>\n"
            + "            </div>\n"
            + "            <!--[if mso | IE]>\n"
            + "            </td>\n"
            + "          </tr>\n"
            + "        </table>\n"
            + "      <![endif]-->\n"
            + "    </div>\n"
            + "  </body>\n"
            + "\n"
            + "</html>";

    return html;
  }

  public static String correoSuccess(String apellidoPaterno, String apellidoMaterno, String nombre, String tipoDoc, String nroDoc) {
    String html = "<!doctype html>\n"
            + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\"\n"
            + "xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
            + "  \n"
            + "  <head>\n"
            + "    <title></title>\n"
            + "    <!--[if !mso]>\n"
            + "      <!-- -->\n"
            + "      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
            + "    <!--<![endif]-->\n"
            + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
            + "    <style type=\"text/css\">\n"
            + "      #outlook a { padding: 0; }\n"
            + "      .ReadMsgBody { width: 100%; }\n"
            + "      .ExternalClass { width: 100%; }\n"
            + "      .ExternalClass * { line-height:100%; }\n"
            + "      body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }\n"
            + "      table, td { border-collapse:collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }\n"
            + "      img { border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }\n"
            + "      p { display: block; margin: 13px 0; }\n"
            + "    </style>\n"
            + "    <!--[if !mso]>\n"
            + "      <!-->\n"
            + "      <style type=\"text/css\">\n"
            + "        @media only screen and (max-width:480px) {\n"
            + "          @-ms-viewport { width:320px; }\n"
            + "          @viewport { width:320px; }\n"
            + "        }\n"
            + "      </style>\n"
            + "    <!--<![endif]-->\n"
            + "    <!--[if mso]>\n"
            + "      <xml>\n"
            + "        <o:OfficeDocumentSettings>\n"
            + "          <o:AllowPNG/>\n"
            + "          <o:PixelsPerInch>96</o:PixelsPerInch>\n"
            + "        </o:OfficeDocumentSettings>\n"
            + "      </xml>\n"
            + "    <![endif]-->\n"
            + "    <!--[if lte mso 11]>\n"
            + "      <style type=\"text/css\">\n"
            + "        .outlook-group-fix {\n"
            + "          width:100% !important;\n"
            + "        }\n"
            + "      </style>\n"
            + "    <![endif]-->\n"
            + "    <!--[if !mso]>\n"
            + "      <!-->\n"
            + "      <link href=\"https://d2yjfm58htokf8.cloudfront.net/static/fonts/averta-v2.css\"\n"
            + "      rel=\"stylesheet\" type=\"text/css\">\n"
            + "      <style type=\"text/css\">\n"
            + "        @import url(https://d2yjfm58htokf8.cloudfront.net/static/fonts/averta-v2.css);\n"
            + "      </style>\n"
            + "    <!--<![endif]-->\n"
            + "    <style type=\"text/css\">\n"
            + "      p {\n"
            + "        margin: 0 0 24px 0;\n"
            + "      }\n"
            + "\n"
            + "      a {\n"
            + "        color: #00b9ff;\n"
            + "      }\n"
            + "\n"
            + "      hr {\n"
            + "        margin: 32px 0;\n"
            + "        border-top: 1px #e2e6e8;\n"
            + "      }\n"
            + "\n"
            + "      dt {\n"
            + "        font-size: 13px;\n"
            + "        margin-left: 0;\n"
            + "      }\n"
            + "\n"
            + "	  dd {\n"
            + "        color: #37517e;\n"
            + "        margin-bottom: 24px;\n"
            + "        margin-left: 0;\n"
            + "      }\n"
            + "\n"
            + "      h5 {\n"
            + "        font-family: TW-Averta-SemiBold, Averta, Helvetica, Arial;\n"
            + "        font-size: 16px;\n"
            + "        line-height: 24px;\n"
            + "        color: #2e4369;\n"
            + "      }\n"
            + "      \n"
            + "      pre {\n"
            + "        display: block;\n"
            + "        padding: 16px;\n"
            + "        padding: 12px 24px;\n"
            + "        margin: 0 0 48px;\n"
            + "        font-size: 14px;\n"
            + "        line-height: 24px;\n"
            + "        color: #4a5860;\n"
            + "        word-break: break-all;\n"
            + "        word-wrap: break-word;\n"
            + "        background-color: #f2f5f7;\n"
            + "        border-radius: 3px;\n"
            + "      }\n"
            + "\n"
            + "      .body-wrapper {\n"
            + "        background: #f2f5f7 url('https://d2yjfm58htokf8.cloudfront.net/static/images/background-v1.png') no-repeat center top;\n"
            + "        padding: 0px;\n"
            + "        margin: auto;\n"
            + "      }\n"
            + "\n"
            + "      .content-wrapper {\n"
            + "        max-width: 536px;\n"
            + "        padding: 32px;\n"
            + "        padding-bottom: 48px;\n"
            + "      }\n"
            + "\n"
            + "      .footer-wrapper div {\n"
            + "        color: #37517e !important;\n"
            + "      }\n"
            + "\n"
            + "      .footer-wrapper div a {\n"
            + "        color: #00b9ff !important;\n"
            + "      }\n"
            + "\n"
            + "      .hero {\n"
            + "        font-family: TW-Averta-Bold, Averta, Helvetica, Arial;\n"
            + "        color: #37517e;\n"
            + "        font-size: 22px;\n"
            + "        line-height: 30px;\n"
            + "      }\n"
            + "\n"
            + "      .page-header {\n"
            + "        border-bottom: 1px solid #eaebed;\n"
            + "        padding-bottom: 16px;\n"
            + "      }\n"
            + "\n"
            + "      .mb-0 {\n"
            + "        margin-bottom: 0 !important;\n"
            + "      }\n"
            + "\n"
            + "      .mt-0 {\n"
            + "        margin-top: 0 !important;\n"
            + "      }\n"
            + "      \n"
            + "      .btn {\n"
            + "        box-sizing: border-box;\n"
            + "        display: inline-block;\n"
            + "        min-height: 36px;\n"
            + "        padding: 12px 24px;\n"
            + "        margin: 0 0 24px;\n"
            + "        font-size: 16px;\n"
            + "        font-weight: 600;\n"
            + "        line-height: 24px;\n"
            + "        text-align: center;\n"
            + "        white-space: nowrap;\n"
            + "        vertical-align: middle;\n"
            + "        cursor: pointer;\n"
            + "        border: 0;\n"
            + "        border-radius: 3px;\n"
            + "        color: #fff;\n"
            + "        background-color: #00b9ff;\n"
            + "        text-decoration: none;\n"
            + "\n"
            + "        -webkit-transition: all .15s ease-in-out;\n"
            + "        -o-transition: all .15s ease-in-out;\n"
            + "        transition: all .15s ease-in-out;\n"
            + "      }\n"
            + "      \n"
            + "      .btn:hover {\n"
            + "        background-color: #00a4df;\n"
            + "      }\n"
            + "      \n"
            + "      .btn:active {\n"
            + "        background-color: #008ec0;\n"
            + "      }\n"
            + "\n"
            + "      @media screen and (min-width: 576px) and (max-width: 768px) {\n"
            + "        .body-wrapper {\n"
            + "          padding: 24px !important;\n"
            + "        }\n"
            + "\n"
            + "        .content-wrapper {\n"
            + "          max-width: 504px !important;\n"
            + "          padding: 48px !important;\n"
            + "        }\n"
            + "      }\n"
            + "\n"
            + "      @media screen and (min-width: 768px) {\n"
            + "        .body-wrapper {\n"
            + "          padding: 48px !important;\n"
            + "        }\n"
            + "\n"
            + "        .content-wrapper {\n"
            + "          max-width: 456px !important;\n"
            + "          padding: 72px !important;\n"
            + "          padding-top: 48px !important;\n"
            + "        }\n"
            + "      }\n"
            + "    </style>\n"
            + "    <style type=\"text/css\">\n"
            + "      @media only screen and (min-width:480px) {\n"
            + "        .mj-column-per-100 { width:100%!important; }\n"
            + "      }\n"
            + "    </style>\n"
            + "  </head>\n"
            + "  \n"
            + "  <body>\n"
            + "    <div class=\"mj-container body-wrapper\">\n"
            + "      <!--[if mso | IE]>\n"
            + "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"\n"
            + "        align=\"center\" style=\"width:600px;\">\n"
            + "          <tr>\n"
            + "            <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\n"
            + "            <![endif]-->\n"
            + "            <div style=\"margin:0px auto;max-width:600px;background:#fff;\" class=\"content-wrapper\"\n"
            + "            data-class=\"content-wrapper\">\n"
            + "              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;background:#fff;\"\n"
            + "              align=\"center\" border=\"0\">\n"
            + "                <tbody>\n"
            + "                  <tr>\n"
            + "                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                      <!--[if mso | IE]>\n"
            + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                          <tr>\n"
            + "                            <td style=\"width:600px;\">\n"
            + "                            <![endif]-->\n"
            + "                            <div style=\"margin:0px auto;max-width:600px;\">\n"
            + "                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;\"\n"
            + "                              align=\"center\" border=\"0\">\n"
            + "                                <tbody>\n"
            + "                                  <tr>\n"
            + "                                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                                      <!--[if mso | IE]>\n"
            + "                                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                                          <tr>\n"
            + "                                            <td style=\"vertical-align:middle;width:600px;\">\n"
            + "                                            <![endif]-->\n"
            + "                                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"vertical-align:middle;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;\">\n"
            + "                                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"vertical-align:middle;\"\n"
            + "                                              width=\"100%\" border=\"0\">\n"
            + "                                                <tbody>\n"
            + "                                                  <tr>\n"
            + "                                                    <td style=\"word-wrap:break-word;font-size:0px;padding:0px;\" align=\"center\">\n"
            + "                                                      <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border-spacing:0px;\"\n"
            + "                                                      align=\"center\" border=\"0\">\n"
            + "                                                        <tbody>\n"
            + "                                                          <tr>\n"
            + "                                                            <td style=\"width:150px;\">\n"
            + "                                                              <img alt=\"Logo\" title=\"\" height=\"auto\" src=\"https://ci4.googleusercontent.com/proxy/kz35gfZhxNZHMQP8iXocbvZ88Ni4xy8oCcCsVJ8ssCLfbeCuqULZkBhBAVqSUuLIkJi6kzoIigLOg8uBC3ZK-WcjyuqeS2Vpm3O8PyO7VgJZE0fkUMU=s0-d-e1-ft#https://farm5.staticflickr.com/4700/24780734787_9712ecc7f6_b.jpg\" style=\"border:none;border-radius:0px;display:block;font-size:13px;outline:none;text-decoration:none;width:100%;height:auto\" width=\"150\" class=\"CToWUd\">\n"
            + "                                                            </td>\n"
            + "                                                          </tr>\n"
            + "                                                        </tbody>\n"
            + "                                                      </table>\n"
            + "                                                    </td>\n"
            + "                                                  </tr>\n"
            + "                                                </tbody>\n"
            + "                                              </table>\n"
            + "                                            </div>\n"
            + "                                            <!--[if mso | IE]>\n"
            + "                                            </td>\n"
            + "                                          </tr>\n"
            + "                                        </table>\n"
            + "                                      <![endif]-->\n"
            + "                                    </td>\n"
            + "                                  </tr>\n"
            + "                                </tbody>\n"
            + "                              </table>\n"
            + "                            </div>\n"
            + "                            <!--[if mso | IE]>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                          <tr>\n"
            + "                            <td style=\"width:600px;\">\n"
            + "                            <![endif]-->\n"
            + "                            <div style=\"margin:0px auto;max-width:600px;\">\n"
            + "                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;\"\n"
            + "                              align=\"center\" border=\"0\">\n"
            + "                                <tbody>\n"
            + "                                  <tr>\n"
            + "                                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                                      <!--[if mso | IE]>\n"
            + "                                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                                          <tr>\n"
            + "                                            <td style=\"vertical-align:top;width:600px;\">\n"
            + "                                            <![endif]-->\n"
            + "                                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;\">\n"
            + "                                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                                                <tbody>\n"
            + "                                                  <tr>\n"
            + "                                                    <td style=\"word-wrap:break-word;font-size:0px;padding:0px;\">\n"
            + "                                                      <div style=\"font-size:1px;line-height:48px;white-space:nowrap;\"> </div>\n"
            + "                                                    </td>\n"
            + "                                                  </tr>\n"
            + "                                                </tbody>\n"
            + "                                              </table>\n"
            + "                                            </div>\n"
            + "                                            <!--[if mso | IE]>\n"
            + "                                            </td>\n"
            + "                                          </tr>\n"
            + "                                        </table>\n"
            + "                                      <![endif]-->\n"
            + "                                    </td>\n"
            + "                                  </tr>\n"
            + "                                </tbody>\n"
            + "                              </table>\n"
            + "                            </div>\n"
            + "                            <!--[if mso | IE]>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                          <tr>\n"
            + "                            <td style=\"width:600px;\">\n"
            + "                            <![endif]-->\n"
            + "                            <div style=\"margin:0px auto;max-width:600px;\">\n"
            + "                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;\"\n"
            + "                              align=\"center\" border=\"0\">\n"
            + "                                <tbody>\n"
            + "                                  <tr>\n"
            + "                                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                                      <!--[if mso | IE]>\n"
            + "                                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                                          <tr>\n"
            + "                                            <td style=\"vertical-align:top;width:600px;\">\n"
            + "                                            <![endif]-->\n"
            + "                                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;\">\n"
            + "                                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                                                <tbody>\n"
            + "                                                  <tr>\n"
            + "                                                    <td style=\"word-wrap:break-word;font-size:0px;padding:0px;\" align=\"left\">\n"
            + "                                                      <div style=\"cursor:auto;color:#5d7079;font-family:TW-Averta-Regular, Averta, Helvetica, Arial;font-size:16px;line-height:24px;letter-spacing:0.4px;text-align:left;\">\n"
            + "                                                        <div align=center>\n"
            + "                                                          <h1>TRISMEGISTO - PLANILLA</h1>\n"
            + "                                                        </div>\n"
            + "                                                        <div align=center>\n"
            + "                                                          <img alt=\"Coinbase\" width=\"80\" src=\"https://www.coinbase.com/assets/app/succeed-green-dcb087e9c6e5265b4c49f75c9c2e1d08bc894bc54816d9a5a476611f631b2929.png\">\n"
            + "                                                        </div>\n"
            + "                                                        <div align=center>\n"
            + "                                                          <b>¡FELICITACIONES!</b>\n"
            + "                                                          <p>Su registro se ha completado con éxito<p/>\n"
            + "                                                        </div>\n"
            + "                                                        <table align=center>\n"
            + "                                                          <thead>\n"
            + "                                                            <tr>\n"
            + "                                                              <th colspan=\"2\" align=center><h5><u>DETALLES</u></h5></th>\n"
            + "                                                            </tr>\n"
            + "                                                          </thead>\n"
            + "                                                          <tbody>\n"
            + "                                                            <tr>\n"
            + "                                                              <td><b>APELLIDO PATERNO:</b></td>\n"
            + "                                                              <td>&nbsp;" + apellidoPaterno.toUpperCase() + "</td>\n"
            + "                                                            </tr>\n"
            + "                                                            <tr>\n"
            + "                                                              <td><b>APELLIDO MATERNO:</b></td>\n"
            + "                                                              <td>&nbsp;" + apellidoMaterno.toUpperCase() + "</td>\n"
            + "                                                            </tr>\n"
            + "                                                            <tr>\n"
            + "                                                              <td><b>NOMBRES:</b></td>\n"
            + "                                                              <td>&nbsp;" + nombre.toUpperCase() + "</td>\n"
            + "                                                            </tr>\n"
            + "                                                            <tr>\n"
            + "                                                              <td><b>TIPO DOCUMENTO:</b></td>\n"
            + "                                                              <td>&nbsp;" + tipoDoc.toUpperCase() + "</td>\n"
            + "                                                            </tr>\n"
            + "                                                            <tr>\n"
            + "                                                              <td><b>NRO DOCUMENTO:</b></td>\n"
            + "                                                              <td>&nbsp;" + nroDoc.toUpperCase() + "</td>\n"
            + "                                                            </tr>                                                            \n"
            + "                                                          </tbody>\n"
            + "                                                        </table>\n"
            + "                                                      </div>\n"
            + "                                                    </td>\n"
            + "                                                  </tr>\n"
            + "                                                </tbody>\n"
            + "                                              </table>\n"
            + "                                            </div>\n"
            + "                                            <!--[if mso | IE]>\n"
            + "                                            </td>\n"
            + "                                          </tr>\n"
            + "                                        </table>\n"
            + "                                      <![endif]-->\n"
            + "                                    </td>\n"
            + "                                  </tr>\n"
            + "                                </tbody>\n"
            + "                              </table>\n"
            + "                            </div>\n"
            + "                            <!--[if mso | IE]>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                        </table>\n"
            + "                      <![endif]-->\n"
            + "                    </td>\n"
            + "                  </tr>\n"
            + "                </tbody>\n"
            + "              </table>\n"
            + "            </div>\n"
            + "            <!--[if mso | IE]>\n"
            + "            </td>\n"
            + "          </tr>\n"
            + "        </table>\n"
            + "      <![endif]-->\n"
            + "      <!--[if mso | IE]>\n"
            + "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"\n"
            + "        align=\"center\" style=\"width:600px;\" class=\"content-wrapper-outlook footer-wrapper-outlook\">\n"
            + "          <tr>\n"
            + "            <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\n"
            + "            <![endif]-->\n"
            + "            \n"
            + "            <!--[if mso | IE]>\n"
            + "            </td>\n"
            + "          </tr>\n"
            + "        </table>\n"
            + "      <![endif]-->\n"
            + "      <!--[if mso | IE]>\n"
            + "        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\"\n"
            + "        align=\"center\" style=\"width:600px;\">\n"
            + "          <tr>\n"
            + "            <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\n"
            + "            <![endif]-->\n"
            + "            <div style=\"margin:0px auto;max-width:600px;background:transparent;\">\n"
            + "              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:0px;width:100%;background:transparent;\"\n"
            + "              align=\"center\" border=\"0\">\n"
            + "                <tbody>\n"
            + "                  <tr>\n"
            + "                    <td style=\"text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px;\">\n"
            + "                      <!--[if mso | IE]>\n"
            + "                        <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n"
            + "                          <tr>\n"
            + "                            <td style=\"vertical-align:top;width:600px;\">\n"
            + "                            <![endif]-->\n"
            + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;\">\n"
            + "                              <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\n"
            + "                                <tbody>\n"
            + "                                  <tr>\n"
            + "                                    <td style=\"word-wrap:break-word;font-size:0px;padding:0px;\" align=\"center\">\n"
            + "                                      <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" style=\"border-collapse:collapse;border-spacing:0px;\"\n"
            + "                                      align=\"center\" border=\"0\">\n"
            + "                                        <tbody>\n"
            + "                                          <tr>\n"
            + "                                            <td style=\"width:1px;\">\n"
            + "                                              <img alt=\"\" title=\"\" height=\"1\" src=\"https://api.transferwise.com/v1/notification-flow/messages/c6180a31-5cdb-477a-8c36-756232726efc/channels/EMAIL/open.gif\"\n"
            + "                                              style=\"border:none;border-radius:0px;display:block;font-size:13px;outline:none;text-decoration:none;width:100%;height:1px;\"\n"
            + "                                              width=\"1\">\n"
            + "                                            </td>\n"
            + "                                          </tr>\n"
            + "                                        </tbody>\n"
            + "                                      </table>\n"
            + "                                    </td>\n"
            + "                                  </tr>\n"
            + "                                </tbody>\n"
            + "                              </table>\n"
            + "                            </div>\n"
            + "                            <!--[if mso | IE]>\n"
            + "                            </td>\n"
            + "                          </tr>\n"
            + "                        </table>\n"
            + "                      <![endif]-->\n"
            + "                    </td>\n"
            + "                  </tr>\n"
            + "                </tbody>\n"
            + "              </table>\n"
            + "            </div>\n"
            + "            <!--[if mso | IE]>\n"
            + "            </td>\n"
            + "          </tr>\n"
            + "        </table>\n"
            + "      <![endif]-->\n"
            + "    </div>\n"
            + "  </body>\n"
            + "\n"
            + "</html>";

    return html;
  }

}
